language: node_js
node_js: 8

matrix:
  include:
    - language: objective-c
      os: osx
      osx_image: xcode9.2
      env:
        - REACT_NATIVE_VERSION=0.53.3
      install:
      - ./scripts/install.ios.sh
      script:
      - ./scripts/ci.ios.sh
    - language: objective-c
      os: osx
      osx_image: xcode9.2
      env:
        - REACT_NATIVE_VERSION=0.51.1
      install:
      - ./scripts/install.ios.sh
      script:
      - ./scripts/ci.ios.sh
    - language: android
      os: linux
      jdk: oraclejdk8
      env:
        - REACT_NATIVE_VERSION=0.51.1
      android:
        components:
          - build-tools-27.0.2
          - build-tools-26.0.2
          - android-27
          - extra-android-m2repository
          - extra-google-google_play_services
          - extra-google-m2repository
          - sys-img-armeabi-v7a-android-27
      install:
      - ./scripts/install.android.sh
      script:
      - ./scripts/ci.android.sh
    # Example Projects
    - language: objective-c
      os: osx
      osx_image: xcode9
      env:
        - REACT_NATIVE_VERSION=0.51.1
      install:
      - ./scripts/install.ios.sh
      script:
      - ./scripts/demo-projects.ios.sh

    # Website
    - language: node_js
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - libstdc++-4.9-dev
      env:
        - NAME='Website - master'
      node_js: 8
      script:
      - scripts/publish-website.sh

branches:
  only:
  - master
before_install:
  - nvm install 8
notifications:
  email: true
  slack:
    secure: ExAwGcI4WlRoi/F2AKMds2eNQZ90susGT2k/CSU1ZQdTL5jaeMW6/i86Uz6Goilnd7qL/1GhlHF9Q48yYtctLVg4zSKH3uclHDDtPfWsF/R7+UWBPYtvhuW2VvL4ota8b0QzUlTz3iS0G3iD4AFqnAZUgYqjSeF1arv+YKOTEXzGyPtj3xjD9TSSjamnSEgGd18RRKpG8FWQr631yOSucikUsYcetV8bUTs6PtjcIC0XK1d1Nv/eMJxSwTQCAptQbxPTO0FBEEH+lQ6H5oQ7mvyNQ7BBUEunUWkUsCh85SsqHLbnCaiPojmI8ICUJBDNSDvzvyt1JJOxnjWtXlLu5xLOQRYeMvr9p66uBMTxTw2LXagSw4bxAf8LHXK/EOssTv+bE6gujNga0FF3jOLTDUZF93OT7TCsrVQrIkiKBl/YoJVc137dz/fUz3wA/JkmqQIV0i9BMUVNYlBGg3J9Omo8nQXTEvqNpYdSfWEm6cZT73kRrdiuittcBXUeWaTkqThmL8KMO5u+InUQhOhhxMmZ/u3DZRTxtHu9ndOdMrWaOmDj4MXpTsml6qelFHMdQoNQubUgdpSb0H0KvGObnQwFR3V2alPT6Ovx1e+XzjBiV2CNP3jHci52JGAlPtGRxctiXUYL9TZYgpJdO/IxJR/lAhA7ZJLsfHGL4LUF65o=
    secure: KyGnFJDelMPoz0MklVWYxYYaMakI/AMSzsLO+3ouF+oksHKAqwWSG7rzbAeb1sQGj0uc3t2cIbRDYMPFCbvnhOC+Z2u2qg6xHlrYsaFO6+yNro0s5WxQ+KvJ4P+VqlqKi9XSE9G+kwDz/0FbERJ5sOnDa8ueZ8KDfJEs/ZZRQmedw3bV1p0WWzJKNRsLk3bIbHYk9UXLcA42/QRlymrhBnwVHr6LZfOE19BV5wHScFp/hGz8ajPo8+KCvgUcM/sCIZbeId8BDMc+W91Tk9YzZcxRP5/upq3Sl3FFrPo8LYrJq+tdCGlnHQDBv+yuEC1WlM90V4bgRLqs0w1QuQsFL3adJvmNXHb80gwShmNaY4aS52/jzgbi+mBX2wVAm0VXwLPXnWDo2iIOGkELGBq3PJwwO8W4ES2m0LfLjOTrYG+PLB5FIWae++gDhHDJ9f9tUSK+SxXVvGHRPXNOnpqecGBYxurQhWDuumpe49S2T8Zx+uotjKYRm9ECW4IL8JIzPEVYkRpSoau/zH6urUacDnfFKtvhYDq89/cc/Y3vwhWY8+ixvQH22+HZc3b54KTY/o67Q3IXsAP/yx7AexvJuh56GCgONPchsJ0PX4lIytzyHKwCzQC2UuqgKismDVTlsdlSijfNnaXN2HEhbugwrXJPP+6Kq/TMlPuDSjfi8OA=
