const path = require('path');
const DetoxRuntimeError = require('../../../../errors/DetoxRuntimeError');
const trimFilename = require('../../../../utils/trimFilename');

class NoConflictPathStrategy {
  constructor() {
    this._nextIndex = 0;
    this._testIndices = new WeakMap();
    this._rootDir = `detox_artifacts.${new Date().toISOString()}`;
  }

  get rootDir() {
    return this._rootDir;
  }

  constructPathForTestArtifact(testSummary, artifactName) {
    const testIndexPrefix = this._getTestIndex(testSummary) + '. ';
    const testArtifactsDirname = trimFilename(testIndexPrefix, testSummary.fullName);
    const testArtifactsDirpath = path.join(this.rootDir, testArtifactsDirname);

    if (testArtifactsDirpath.startsWith('..')) {
      throw new DetoxRuntimeError({
        message: `Autogenerated artifact directory (${testArtifactsDirpath}) should not be outside of the --artifacts-location root`,
        hint: `Don't use ".." in test titles and descriptions: ${testSummary.fullName}`
      });
    }

    const artifactPath = path.join(testArtifactsDirpath, artifactName.slice(0, 255));
    if (artifactPath.startsWith('..')) {
      throw new DetoxRuntimeError({
        message: `Artifact path (${artifactPath}) should not be outside of the --artifacts-location root`,
        hint: `Don't use ".." in artifact names`,
      });
    }

    return artifactPath;
  }

  _getTestIndex(testSummary) {
    if (!this._testIndices.has(testSummary)) {
      this._testIndices.set(testSummary, this._nextIndex);
      return this._nextIndex++;
    }

    return this._testIndices.get(testSummary);
  }
}

module.exports = NoConflictPathStrategy;
