const path = require('path');
const DetoxRuntimeError = require('../errors/DetoxRuntimeError');
const trimFilename = require('../utils/trimFilename');

class NoConflictArtifactsPathsProvider {
  constructor() {
    this._nextIndex = 0;
    this._testIndices = new WeakMap();
    this.rootDir = `detox_artifacts.${new Date().toISOString()}`;
  }

  constructPathForTestArtifact(testInfo, artifactName) {
    const testIndexPrefix = this._getTestIndex(testInfo) + '. ';
    const testArtifactsDirname = trimFilename(testIndexPrefix, testInfo.fullTitle);
    const testArtifactsDirpath = path.join(this.rootDir, testArtifactsDirname);

    if (testArtifactsDirpath.startsWith('..')) {
      throw new DetoxRuntimeError({
        message: `Autogenerated artifact directory (${testArtifactsDirpath}) should not be outside of the --artifacts-location root`,
        hint: `Don't use ".." in test titles and descriptions: ${testInfo.fullTitle}`
      });
    }

    const artifactPath = path.join(testArtifactsDirpath, artifactName.slice(0, 255));
    if (artifactPath.startsWith('..')) {
      throw new DetoxRuntimeError({
        message: `Artifact path (${artifactPath}) should not be outside of the --artifacts-location root`,
        hint: `Don't use ".." in artifact names`,
      });
    }

    return artifactPath;
  }

  _getTestIndex(testInfo) {
    if (!this._testIndices.has(testInfo)) {
      this._testIndices.set(testInfo, this._nextIndex);
      return this._nextIndex++;
    }

    return this._testIndices.get(testInfo);
  }
}


module.exports = NoConflictArtifactsPathsProvider;
